# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    types:
      - closed
    branches: 
      - "main"
env:
  AWS_REGION: ${{secrets.AWS_DEFAULT_REGION}}
  SERVER_KEY: ${{secrets.SERVER_KEY}}
  SERVER_HOST: ${{secrets.SERVER_HOST}}
  SERVER_USERNAME: ${{secrets.SERVER_USERNAME}}
  SERVER_DEPLOY_TARGET: ${{secrets.SERVER_DEPLOY_TARGET}}
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Deploy to server on master
    runs-on: ubuntu-latest
    environment: Production
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4.0.1
      with:
        role-to-assume: arn:aws:iam::160365616731:role/GithubActions-AssumeRoleWithActions #change to reflect your IAM role’s ARN
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ env.AWS_REGION }}
    - name: Sts GetCallerIdentity
      run: |
          aws sts get-caller-identity
  
    - name: Get Public IP
      id: ip
      uses: haythem/public-ip@v1.3
      
    - name: Add Github Actions IP to Security group
      run: |
        aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

    - name: "Checkout files"
      uses: actions/checkout@v3
  
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          TARGET: ${{ secrets.SERVER_DEPLOY_TARGET }}
    - name: Remove Github Actions IP from security group
      run: |
        aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
    
