# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run build --if-present
    - name: Use Node.js ${{ matrix.node-version }}
      uses: burnett01/rsync-deployments@5.1
      with:
          switches: -avzr --delete
          path: ./*
          remote_path: /var/www/html/web2.dazadev.online
          remote_host: ec2-34-224-220-225.compute-1.amazonaws.com
          remote_user: ubuntu
          remote_key: "${{ secrets.SSH_PRIVATE_KEY }}"
    
